# .github/workflows/build-app-graph.yml
name: Build Application Graph

on:
  push:
    branches: [main]
    paths: [app.bicep]
  pull_request:
    paths: [app.bicep]

permissions:
  contents: write

jobs:
  build-graph:
    uses: nithyatsu/radius/.github/workflows/__build-app-graph.yml@pr-graph-view-fix
    with:
      app_file: app.bicep
      orphan_branch: radius-graph
      workflow_source_ref: pr-graph-view-fix
